version: '3.3'

services:
  server:
    image: registry.gitlab.com/gametactic/authentication:latest
    environment:
      - APP_ENV=prod
      - JWT_SECRET_KEY=/run/secrets/jwt_private
      - JWT_PUBLIC_KEY=/run/secrets/jwt_public
      - JWT_PASSPHRASE=<PASSPHRASE>
      - DATABASE_URL=mysql://gt_auth:<PASS>@<HOST>/gt_auth
      - GUARD_WG=<WARGAMING_TOKEN>
      - TRUSTED_HOSTS=^auth.eu.gametactic.eu$$
    deploy:
      replicas: 1
      labels:
        traefik.http.routers.auth-ssl.tls: 'true'
        traefik.http.routers.auth.entrypoints: web
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.http.routers.auth-ssl.tls.certresolver: le
        traefik.http.routers.auth-ssl.rule: Host(`auth.eu.gametactic.eu`)
        traefik.http.routers.auth-ssl.entrypoints: websecure
        traefik.http.services.auth.loadbalancer.server.port: '80'
        traefik.http.routers.auth.rule: Host(`auth.eu.gametactic.eu`)
        traefik.enable: 'true'
    networks:
      - GT_PUB
      - GT_DB
    secrets:
      - jwt_private
      - jwt_public

networks:
  GT_PUB:
    external: true
  GT_DB:
    external: true

secrets:
  jwt_private:
    external: true
  jwt_public:
    external: true
