version: '3.3'
services:
  redis:
    image: thomasjpfan/redis-look:latest
    environment:
      REDIS_MASTER_NAME: redismaster
      REDIS_SENTINEL_IP: redis-sentinel
      REDIS_SENTINEL_PORT: '26379'
    networks:
     - GT_REDIS
    logging:
      driver: json-file
    deploy:
      replicas: 3
  redis-sentinel:
    image: thomasjpfan/redis-sentinel:latest
    environment:
      REDIS_IP: redis-zero
      REDIS_MASTER_NAME: redismaster
    networks:
     - GT_REDIS
    logging:
      driver: json-file
    deploy:
      replicas: 3
networks:
  GT_REDIS:
    external: true
