version: '3.3'
services:
  server:
    image: registry.gitlab.com/gametactic/users:latest
    environment:
      APP_ENV: prod
      DATABASE_URL: mysql://<DB_USER>:<DB_PASS>@<DB_HOST>/<DB>
      GUARD_WG: <SECRET>
      JWT_PASSPHRASE: <SECRET>
      JWT_PUBLIC_KEY: /run/secrets/jwt_public
      JWT_SECRET_KEY: /run/secrets/jwt_private
      TRUSTED_HOSTS: ^user.eu.gametactic.eu$
    networks:
     - GT_DB
     - GT_PUB
    secrets:
     - jwt_private
     - jwt_public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.user.entrypoints: web
        traefik.http.routers.user-ssl.tls.certresolver: le
        swarmpit.service.deployment.autoredeploy: 'true'
        traefik.http.services.user.loadbalancer.server.port: '80'
        traefik.http.routers.user.rule: Host(`user.eu.gametactic.eu`)
        traefik.http.routers.user-ssl.tls: 'true'
        traefik.http.routers.user-ssl.entrypoints: websecure
        traefik.http.routers.user-ssl.rule: Host(`user.eu.gametactic.eu`)
        traefik.enable: 'true'
networks:
  GT_DB:
    external: true
  GT_PUB:
    external: true
secrets:
  jwt_private:
    external: true
  jwt_public:
    external: true
